repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: go-imports
  - repo: git://github.com/Bahjat/pre-commit-golang
    rev: 85c26d4d1c8a086095a057bbdf8adf56af603ce4
    hooks:
      - id: go-lint
  - repo: git://github.com/arielcr/pre-commit-golang
    rev: d04f634ae356e4c51c5e4aa5a5cfe32e80426e13
    hooks:
      - id: go-unit-tests